name: nexus_training_tracker
description: "Nexus Training Tracker - Enterprise-grade internal platform for professional development and learning management"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  charts_flutter: ^0.12.0
  cloud_firestore: ^4.14.0
  dio: ^5.3.0
  equatable: ^2.0.5
  firebase_auth: ^4.10.0
  firebase_core: ^2.17.0
  firebase_storage: ^11.2.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  get_it: ^7.6.0
  go_router: ^12.0.0
  google_fonts: ^6.1.0
  hive: ^2.2.0
  http: ^1.1.0
  intl: ^0.17.0
  json_serializable: ^6.7.0
  logger: ^2.1.0
  pdf: ^3.10.0
  provider: ^6.0.0
  riverpod: ^2.4.0
  sqflite: ^2.3.0
  syncfusion_flutter_charts: ^21.2.4
  uuid: ^4.0.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  mockito: ^5.4.4

flutter:
  uses-material-design: true
