name: internal_training_tracker
description: "Enterprise-grade Internal Training Tracker for HR and Management"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  
  # State Management
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  
  # Charts
  fl_chart: ^0.70.2
  
  # Animations
  flutter_animate: ^4.5.2
  
  # Utils
  intl: ^0.20.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
